#ifndef __MCEVENT_H
#define __MCEVENT_H

enum MCEvent_t {
  EVENT_NOOP,
  EVENT_ARM,
  EVENT_DISARM,
  EVENT_START_COUNTDOWN,
  EVENT_RESET_COUNTDOWN,
  EVENT_AT_ZERO,
  EVENT_LAUNCH,
  EVENT_DONE_LAUNCHING,

  EVENT_TIMER_EXPIRED,

  EVENT_START_MUSIC,
  EVENT_STOP_MUSIC,
};

#endif